name: Add Environment Variables
description: Add environment variables to the workflow environment


inputs:
  vars:
    description: Vars context value
    required: true
  secrets:
    description: Secrets context value
    required: true
  prefix:
    description: Prefix for environment variables
    required: true


runs:
  using: composite
  steps:
    - name: Add Environment Variables
      shell: bash
      run: |
        echo "${{ toJSON(inputs.vars) }}" | jq -r --arg prefix ${{ inputs.prefix }} 'to_entries
          | map(select(.key | startswith("$prefix")) | "\("$prefix" + (.key | ltrimstr("$prefix") | ascii_downcase))=\(.value)")
          | .[]' >> $GITHUB_ENV
        echo "${{ toJSON(inputs.secrets) }}" | jq -r --arg prefix ${{ inputs.prefix }} 'to_entries
          | map(select(.key | startswith("$prefix")) | "\("$prefix" + (.key | ltrimstr("$prefix") | ascii_downcase))=\(.value)")
          | .[]' >> $GITHUB_ENV
